branches :
  only :
    - master
language : node_js
node_js :
  - 9
install :
  - npm install
  - npm install codeclimate-test-reporter -g
script :
  - npm run lint
  - npm run coverage
after_script :
  - codeclimate-test-reporter < coverage/lcov.info
